### ISSUE TITLE
newline in Paragraphs()?

### ISSUE THREAD

**Issue by quillaja** [go-loremipsum/loremipsum#6]
Shouldn't paragraphs be joined with `\n` instead of `\\n` in `Paragraphs()`?  I tried to use it in a function that wraps/breaks lines on `\n` like you'd normally write in a string (eg "line one\nline two") and was getting literal "\n" printed in my document.
```go
// Paragraphs returns paragraphs of lorem ipsum
func (li *LoremIpsum) Paragraphs(count int) string {
	return strings.Join(li.ParagraphList(count), "\\n")
}
```

**Comment by tomi77** [comment]
fixed in v1.1.1. Thanks
